// Desktop build — three esbuild bundles + one generated file, all written to dist/:
//
//   main.js           Electron main process (CJS; electron external)
//   preload.js        Electron preload (CJS; electron external)
//   server.mjs        the Rigel Node server, re-bundled from apps/server/src/index.ts
//   server-entry.mjs  parent-death watchdog wrapper that imports server.mjs
//
// Why we re-bundle the server here (instead of forking apps/server's own bundle
// or its TypeScript via tsx):
//   • Electron's utilityProcess ESM loader does NOT activate tsx's loader hooks
//     (`--import tsx` is passed through but the extensionless TS imports still
//     ERR_MODULE_NOT_FOUND), so forking the .ts entry doesn't work under Electron.
//   • apps/server's own bundle is ESM and relies on esbuild's __require shim for
//     Node builtins (pulled in by `ws`); under Electron's utility ESM context
//     that shim throws "Dynamic require of 'events' is not supported".
// So we produce a desktop-OWNED server.mjs that injects a real createRequire-backed
// `require` via a banner (fixes the dynamic-require), keeps node-pty external (it's
// a native addon — can't be bundled, and a desktop dep makes it resolvable next to
// this bundle), and is a normal ESM module Electron's utility loader accepts.
// This does NOT modify apps/server (no source/build-script edits).
import { build } from "esbuild";

const electronBundles = build({
  entryPoints: ["src/main.ts", "src/preload.ts"],
  outdir: "dist",
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node22",
  external: ["electron"],
  logLevel: "info",
});

const serverBundle = build({
  entryPoints: ["../server/src/index.ts"],
  outfile: "dist/server.mjs",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  // node-pty is a native N-API addon — never bundle it. Resolved at runtime from
  // apps/desktop/node_modules/node-pty (pinned to 1.1.0 — same as apps/server —
  // so both packages share the same ABI-compatible binary), so `import "node-pty"`
  // resolves next to this file.
  // `electron` is external so secretStore.ts's `require("electron")` resolves at
  // runtime from the Electron utility process (where safeStorage lives) instead of
  // being bundled — matching electronBundles above.
  external: ["node-pty", "electron"],
  // Give the ESM bundle a real CommonJS `require` so esbuild's interop shim can
  // load Node builtins (events/stream/etc. via `ws`) under Electron's utility
  // ESM loader, which otherwise rejects esbuild's default dynamic-require shim.
  banner: {
    js: "import { createRequire as __rigelCreateRequire } from 'node:module'; const require = __rigelCreateRequire(import.meta.url);",
  },
  logLevel: "info",
});

// The chat permission hook. claudeBridge.ts registers a PreToolUse hook command
// `node --import tsx <import.meta.url>/../permissionHook.ts` — i.e. it expects a
// permissionHook.ts SIBLING of the running server bundle. We emit a self-contained
// bundle under the name the server hardcodes (.ts), so the hook resolves next to
// dist/server.mjs and live AI chat's mutation-gating works. (tsx passes already-
// valid JS through unchanged, so the .ts extension is fine.)
const permissionHookBundle = build({
  entryPoints: ["../server/src/permissionHook.ts"],
  outfile: "dist/permissionHook.ts",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  allowOverwrite: true,
  logLevel: "info",
});

// Same self-contained hook bundle, but emitted with a `.mjs` extension. The
// PACKAGED desktop app has no node/tsx on PATH, so it overrides the hook command
// (via HELMSMAN_HOOK_CMD in main.ts) to run THIS file directly with Electron's
// own Node (`electron --run-as-node permissionHook.mjs`) — no tsx needed, since
// `.mjs` is plain ESM. Dev/Docker keep using the `.ts` above (default command).
const permissionHookMjsBundle = build({
  entryPoints: ["../server/src/permissionHook.ts"],
  outfile: "dist/permissionHook.mjs",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  allowOverwrite: true,
  logLevel: "info",
});

// C2 / parent-death watchdog: dist/server-entry.mjs is what forkServer actually
// forks. It captures the parent (Electron main) PID at startup and polls every
// 2 s; if the parent is gone (SIGKILL, crash) it sends itself SIGTERM so the
// server's existing SIGTERM hook (portForwards.stopAll → process.exit) runs,
// reaping kubectl/PTY children instead of leaving orphans. The interval is
// unref()'d so it never prevents the server from exiting naturally.
import { mkdirSync, writeFileSync } from "node:fs";
// esbuild's build() calls above create dist/, but they're async and awaited at
// the end — this synchronous write runs first, so on a CLEAN checkout (CI) dist/
// doesn't exist yet → ENOENT. Ensure it exists before writing.
mkdirSync("dist", { recursive: true });
writeFileSync(
  "dist/server-entry.mjs",
  `// Auto-generated by build.mjs — parent-death watchdog for the Rigel desktop server.
// Do not edit manually; it is regenerated on every "pnpm build".
const PARENT = process.ppid;
setInterval(() => {
  try { process.kill(PARENT, 0); } catch { process.kill(process.pid, "SIGTERM"); }
}, 2000).unref();
await import("./server.mjs");
`,
);

await Promise.all([electronBundles, serverBundle, permissionHookBundle, permissionHookMjsBundle]);
