// SF Symbol (iconSystemName) → Font Awesome icon mapping for catalog cards.
// Best-effort (docs/parity/catalog.md §"Icon Mapping"); unknown names fall back
// to faBox.
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faBox,
  faLock,
  faDatabase,
  faBullhorn,
  faChartColumn,
  faFolder,
  faFileLines,
  faServer,
  faCloud,
  faGlobe,
  faNetworkWired,
  faShieldCheck,
  faKey,
  faEnvelope,
  faMessage,
  faImage,
  faFilm,
  faFlag,
  faMusic,
  faBug,
  faCodeBranch,
  faWaveform,
  faBell,
  faBoxesStacked,
  faCalendar,
  faChartBar,
  faCode,
  faEye,
  faGauge,
  faHardDrive,
  faLayerGroup,
  faChartLine,
  faLink,
  faNewspaper,
  faMagnifyingGlass,
  faPaperPlane,
  faShareNodes,
  faSparkles,
  faTerminal,
  faUsers,
  faDiagramProject,
} from "@awesome.me/kit-6050953220/icons/classic/solid";

/**
 * Map an SF Symbol name to a Font Awesome icon. The catalog ships Apple SF Symbol
 * names; we translate by leading token, falling back to faBox for anything
 * unmapped so a card always renders an icon.
 */
const MAP: Record<string, IconDefinition> = {
  // explicit catalog symbols seen in the data
  "lock.circle.fill": faLock,
  "lock.shield.fill": faShieldCheck,
  "lock.fill": faLock,
  "key.fill": faKey,
  "key.horizontal.fill": faKey,
  "database.fill": faDatabase,
  "cylinder.split.1x2.fill": faDatabase,
  "externaldrive.fill": faHardDrive,
  "internaldrive.fill": faHardDrive,
  "megaphone.fill": faBullhorn,
  "chart.bar.fill": faChartColumn,
  "chart.bar.xaxis": faChartBar,
  "chart.line.uptrend.xyaxis": faChartLine,
  "chart.xyaxis.line": faChartLine,
  "waveform.path.ecg": faWaveform,
  "gauge": faGauge,
  "gauge.medium": faGauge,
  "speedometer": faGauge,
  "folder.fill": faFolder,
  "doc.text.fill": faFileLines,
  "doc.richtext.fill": faFileLines,
  "newspaper.fill": faNewspaper,
  "server.rack": faServer,
  "cloud.fill": faCloud,
  "globe": faGlobe,
  "network": faNetworkWired,
  "point.3.connected.trianglepath.dotted": faNetworkWired,
  "envelope.fill": faEnvelope,
  "message.fill": faMessage,
  "bubble.left.fill": faMessage,
  "photo.fill": faImage,
  "photo.stack.fill": faImage,
  "film.fill": faFilm,
  "play.rectangle.fill": faFilm,
  "music.note": faMusic,
  "ant.fill": faBug,
  "ladybug.fill": faBug,
  "arrow.triangle.branch": faCodeBranch,
  "flag.fill": faFlag,
  "flag.2.crossed.fill": faFlag,
  "shippingbox.fill": faBox,
  "cube.box.fill": faBoxesStacked,
  "bell.fill": faBell,
  "calendar": faCalendar,
  "chevron.left.forwardslash.chevron.right": faCode,
  "curlybraces": faCode,
  "terminal.fill": faTerminal,
  "eye.fill": faEye,
  "magnifyingglass": faMagnifyingGlass,
  "paperplane.fill": faPaperPlane,
  "square.and.arrow.up.fill": faShareNodes,
  "sparkles": faSparkles,
  "person.3.fill": faUsers,
  "person.2.fill": faUsers,
  "flowchart.fill": faDiagramProject,
  "link": faLink,
  "square.stack.3d.up.fill": faLayerGroup,
};

export function iconFor(iconSystemName: string): IconDefinition {
  return MAP[iconSystemName] ?? faBox;
}
