// SF Symbol (iconSystemName) → Lucide icon mapping for catalog cards. Best-effort
// (docs/parity/catalog.md §"Icon Mapping"); unknown names fall back to Package.
import {
  Package,
  Lock,
  Database,
  Megaphone,
  BarChart3,
  Folder,
  FileText,
  Server,
  Cloud,
  Globe,
  Network,
  ShieldCheck,
  KeyRound,
  Mail,
  MessageSquare,
  Image,
  Film,
  Music,
  Bug,
  GitBranch,
  Container,
  Activity,
  Bell,
  Boxes,
  Calendar,
  ChartBar,
  Code,
  Eye,
  Gauge,
  HardDrive,
  Layers,
  LineChart,
  Link as LinkIcon,
  Newspaper,
  Search,
  Send,
  Share2,
  Sparkles,
  Terminal,
  Users,
  Workflow,
  type LucideIcon,
} from "lucide-react";

/**
 * Map an SF Symbol name to a Lucide icon. The catalog ships Apple SF Symbol
 * names; we translate by leading token, falling back to Package for anything
 * unmapped so a card always renders an icon.
 */
const MAP: Record<string, LucideIcon> = {
  // explicit catalog symbols seen in the data
  "lock.circle.fill": Lock,
  "lock.shield.fill": ShieldCheck,
  "lock.fill": Lock,
  "key.fill": KeyRound,
  "key.horizontal.fill": KeyRound,
  "database.fill": Database,
  "cylinder.split.1x2.fill": Database,
  "externaldrive.fill": HardDrive,
  "internaldrive.fill": HardDrive,
  "megaphone.fill": Megaphone,
  "chart.bar.fill": BarChart3,
  "chart.bar.xaxis": ChartBar,
  "chart.line.uptrend.xyaxis": LineChart,
  "chart.xyaxis.line": LineChart,
  "waveform.path.ecg": Activity,
  "gauge": Gauge,
  "gauge.medium": Gauge,
  "speedometer": Gauge,
  "folder.fill": Folder,
  "doc.text.fill": FileText,
  "doc.richtext.fill": FileText,
  "newspaper.fill": Newspaper,
  "server.rack": Server,
  "cloud.fill": Cloud,
  "globe": Globe,
  "network": Network,
  "point.3.connected.trianglepath.dotted": Network,
  "envelope.fill": Mail,
  "message.fill": MessageSquare,
  "bubble.left.fill": MessageSquare,
  "photo.fill": Image,
  "photo.stack.fill": Image,
  "film.fill": Film,
  "play.rectangle.fill": Film,
  "music.note": Music,
  "ant.fill": Bug,
  "ladybug.fill": Bug,
  "arrow.triangle.branch": GitBranch,
  "shippingbox.fill": Container,
  "cube.box.fill": Boxes,
  "bell.fill": Bell,
  "calendar": Calendar,
  "chevron.left.forwardslash.chevron.right": Code,
  "curlybraces": Code,
  "terminal.fill": Terminal,
  "eye.fill": Eye,
  "magnifyingglass": Search,
  "paperplane.fill": Send,
  "square.and.arrow.up.fill": Share2,
  "sparkles": Sparkles,
  "person.3.fill": Users,
  "person.2.fill": Users,
  "flowchart.fill": Workflow,
  "link": LinkIcon,
  "square.stack.3d.up.fill": Layers,
};

export function iconFor(iconSystemName: string): LucideIcon {
  return MAP[iconSystemName] ?? Package;
}
