apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helmsman-marketing
  namespace: default
  labels:
    app: helmsman-marketing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  - host: rigel.run
    http:
      paths:
      - backend:
          service:
            name: helmsman-marketing
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - rigel.run
    secretName: helmsman-marketing-tls